# API
procergs_login_cidadao_api_core:
    resource: "@PROCERGSLoginCidadaoAPIBundle/Controller"
    defaults: { _format: json }
    prefix:   /

procergs_login_cidadao_Notification:
    type: rest
    prefix: /
    resource: "@PROCERGSLoginCidadaoAPIBundle/Controller/NotificationController.php"
    name_prefix: api_1_
    defaults: { _format: json }

procergs_login_cidadao_NotificationCallback:
    type: rest
    prefix: /
    resource: "@PROCERGSLoginCidadaoAPIBundle/Controller/NotificationCallbackController.php"
    name_prefix: api_1_
    defaults: { _format: json }

procergs_login_cidadao_Person:
    type: rest
    prefix: /
    resource: "@PROCERGSLoginCidadaoAPIBundle/Controller/PersonController.php"
    defaults: { _format: json }

procergs_login_cidadao_Badge:
    type: rest
    prefix: /
    resource: "@PROCERGSLoginCidadaoAPIBundle/Controller/BadgeController.php"
    defaults: { _format: json }

procergs_login_cidadao_PersonAddress:
    type: rest
    prefix: /
    resource: "@PROCERGSLoginCidadaoAPIBundle/Controller/PersonAddressController.php"
    name_prefix: api_1_
    defaults: { _format: json }