security:
    encoders:
        Symfony\Component\Security\Core\User\User: sha512
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chainprovider:
            chain:
                providers: [fos_userbundle, fos_facebook_provider]
        fos_userbundle:
            id: procergs_logincidadao.user_provider
        fos_facebook_provider:
            id: fos_facebook.user.login
#        fos_twitter_provider:
#            id: fos_twitter.user

    firewalls:
        oauth_token:
            pattern:  ^/oauth/v2/token
            security: false

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/(?!api|!oauth)

            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~

            fos_facebook:
                app_url: ""
                server_url: "http://lc.des.dona.to"
                login_path: /login
                check_path: /facebook/login_check
                default_target_path: fos_user_profile_edit
                success_handler: security.authentication.success_handler
                provider: fos_facebook_provider

            oauth:
                resource_owners:
                    twitter:    "/login/check-twitter"
                login_path:   /login
                use_forward:  false
                failure_path: /login
                default_target_path: fos_user_profile_edit
                success_handler: security.authentication.success_handler
                oauth_user_provider:
                    service:  procergs.hwi_twitter.user_provider

            form_login:
                provider:       fos_userbundle
                csrf_provider:  form.csrf_provider
                login_path:     /login
                use_forward:    false
                check_path:     /login_check
                username_parameter: login_form_type[username]
                password_parameter: login_form_type[password]
                csrf_parameter: login_form_type[csrf_token]
                always_use_default_target_path: false
                default_target_path:            fos_user_profile_edit
                target_path_parameter:          _target_path
                use_referer:                    true

            logout:
                path: /logout
            anonymous:  true

        oauth_authorize:
            pattern:  ^/oauth/v2/auth
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                check_path: /oauth/v2/auth_login_check
                login_path: /oauth/v2/auth_login
                always_use_default_target_path: false
                default_target_path:            fos_user_profile_edit
                target_path_parameter:          _target_path
                use_referer:                    true
            anonymous: false


        api:
          pattern:    ^/api/v1(?!/public)
          fos_oauth:  true
          stateless:  true
          anonymous:  true

    access_control:
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
        - { path: ^/api/v1/public/lc_consultaCep2, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/oauth$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/nfg, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect/twitter$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login/facebook$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/contact$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/general$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/privacy$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/about$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/help$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/person/checkEmailAvailable, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/job, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/external/navbar.js, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout/if-not-remembered, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/, roles: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/profile/edit, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/profile/change-username, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/profile/change-password, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin, role: [IS_AUTHENTICATED_FULLY, ROLE_ADMIN] }
        - { path: ^/person, role: IS_AUTHENTICATED_REMEMBERED }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }

        #- { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ], requires_channel: https }
        #- { path: ^/oauth$, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/nfg, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/connect/twitter$, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/login/facebook$, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/contact$, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/general$, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/privacy$, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/about$, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/help$, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/person/checkEmailAvailable, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/job, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/external/navbar.js, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }

        #- { path: ^/, roles: IS_AUTHENTICATED_REMEMBERED, requires_channel: https }
        #- { path: ^/profile/edit, roles: IS_AUTHENTICATED_FULLY, requires_channel: https }
        #- { path: ^/profile/change-username, roles: IS_AUTHENTICATED_FULLY, requires_channel: https }
        #- { path: ^/profile/change-password, roles: IS_AUTHENTICATED_FULLY, requires_channel: https }
        #- { path: ^/admin/, role: [IS_AUTHENTICATED_FULLY, ROLE_ADMIN], requires_channel: https }
        #- { path: ^/person, role: IS_AUTHENTICATED_REMEMBERED, requires_channel: https }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }

