procergs_login_cidadao_notification:
    resource: "@PROCERGSLoginCidadaoNotificationBundle/Controller/"
    type:     annotation
    prefix:   /

procergs_login_cidadao_notification_jsapi:
    resource: "@PROCERGSLoginCidadaoNotificationBundle/Controller/JsAPI/NotificationController.php"
    prefix:   /jsapi/v1
    type: rest
    defaults: { _format: json }
