parameters:
    security.authentication.success_handler.class: PROCERGS\LoginCidadao\CoreBundle\Handler\AuthenticationSuccessHandler
    notifications.helper.class: PROCERGS\LoginCidadao\CoreBundle\Helper\NotificationsHelper
    background.helper.class: PROCERGS\LoginCidadao\CoreBundle\Helper\BackgroundImageHelper
    fos_facebook.user.login.class: PROCERGS\LoginCidadao\CoreBundle\Security\User\Provider\FacebookProvider
    procergs.hwi_twitter.user_provider.class: PROCERGS\LoginCidadao\CoreBundle\Security\User\Provider\FOSUBUserProvider
    procergs_person.registration.form.type.class: PROCERGS\LoginCidadao\CoreBundle\Form\Type\RegistrationFormType
    procergs_person.profile.form.type.class: PROCERGS\LoginCidadao\CoreBundle\Form\Type\ProfileFormType
    procergs_person.revoke_authorization.form.type.class: PROCERGS\LoginCidadao\CoreBundle\Form\Type\RevokeAuthorizationFormType
    procergs_person.resetting.form.type.class: PROCERGS\LoginCidadao\CoreBundle\Form\Type\ResettingFormType
    procergs_logincidadao.change.password.form.type.class: PROCERGS\LoginCidadao\CoreBundle\Form\Type\ChangePasswordFormType
    procergs_logincidadao.user_provider.class: PROCERGS\LoginCidadao\CoreBundle\Security\User\Provider\LoginCidadaoProvider
    procergs_logincidadao.user_manager.class: PROCERGS\LoginCidadao\CoreBundle\Security\User\Manager\UserManager
    procergs_logincidadao.user_register.class: PROCERGS\LoginCidadao\CoreBundle\EventListener\RegisterListner
    procergs_logincidadao.profile_edit.class: PROCERGS\LoginCidadao\CoreBundle\EventListener\ProfileEditListner
    procergs_logincidadao.change.password.listener.class: PROCERGS\LoginCidadao\CoreBundle\EventListener\ChangePasswordListener
    procergs_logincidadao.resetting.listener.class: PROCERGS\LoginCidadao\CoreBundle\EventListener\ResettingListener
    procergs_logincidadao.dne.class: PROCERGS\LoginCidadao\CoreBundle\Helper\DneHelper
    procergs_logincidadao.mailer.class: PROCERGS\LoginCidadao\CoreBundle\Mailer\TwigSwiftMailer
    kernel.listener.logged_in_user_listener.class: PROCERGS\LoginCidadao\CoreBundle\EventListener\LoggedInUserListener
    kernel.listener.exceptions_listener.class: PROCERGS\LoginCidadao\CoreBundle\EventListener\ExceptionListener

    procergs_logincidadao_core.emailChanged.template: PROCERGSLoginCidadaoCoreBundle:Person:emailChangedMessage.html.twig
    procergs_logincidadao.nfgws.class: PROCERGS\LoginCidadao\CoreBundle\Helper\NfgWsHelper

    procergs_logincidadao.postalcode.search.form.type.class: PROCERGS\LoginCidadao\CoreBundle\Form\Type\SearchPostalCodeFormType

services:
    security.authentication.success_handler:
        class: %security.authentication.success_handler.class%
        public: false
        arguments: ["@router", [], "@doctrine.orm.entity_manager", "@session", "@security.http_utils", "@notifications.helper"]
        calls:
            - [setContainer, ["@service_container"]]

    notifications.helper:
        class: %notifications.helper.class%
        arguments: ["@doctrine.orm.entity_manager", "@security.context", "@service_container"]

    background.helper:
        class: %background.helper.class%
        arguments: ["@doctrine.orm.entity_manager", %background_picture.author%, %background_picture.link%, 'wp.jpg']

    fos_facebook.user.login:
        class: %fos_facebook.user.login.class%
        arguments:
            facebook: "@fos_facebook.api"
            userManager: "@fos_user.user_manager"
            validator: "@validator"
            container: "@service_container"
            dispatcher: "@event_dispatcher"
            formFactory: "@fos_user.registration.form.factory"

    procergs.hwi_twitter.user_provider:
        class: %procergs.hwi_twitter.user_provider.class%
        arguments: [ "@fos_user.user_manager", "@session", "@event_dispatcher", "@service_container", "@fos_user.registration.form.factory", { twitter: twitterId }, %http_proxy% ]

    procergs_person.registration.form.type:
        class: %procergs_person.registration.form.type.class%
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: procergs_person_registration }

    procergs_person.profile.form.type:
        class: %procergs_person.profile.form.type.class%
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: procergs_person_profile }

    procergs_person.revoke_authorization.form.type:
        class: %procergs_person.revoke_authorization.form.type.class%
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: procergs_revoke_authorization }

    procergs_person.resetting.form.type:
        class: %procergs_person.resetting.form.type.class%
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: procergs_person_resetting }

    procergs_logincidadao.postalcode.search.form.type:
        class: %procergs_logincidadao.postalcode.search.form.type.class%
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: search_postalcode_form_type }
        calls:
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]

    procergs_logincidadao.user_provider:
        class: %procergs_logincidadao.user_provider.class%
        arguments: ["@fos_user.user_manager"]

    procergs_logincidadao.user_manager:
        class: %procergs_logincidadao.user_manager.class%
        arguments: ["@security.encoder_factory", "@fos_user.util.username_canonicalizer", "@fos_user.util.email_canonicalizer", "@fos_user.entity_manager", %user.class%, "@service_container"]

    procergs_logincidadao.login.form.type:
        class: PROCERGS\LoginCidadao\CoreBundle\Form\Type\LoginFormType
        tags:
            - { name: form.type, alias: login_form_type }
        calls:
            - [setContainer, ["@service_container"]]

    procergs_logincidadao.login.twig.extension:
        class: PROCERGS\LoginCidadao\CoreBundle\Twig\Extension\LoginCidadaoExtension
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension, alias: login_twig_extension }

    procergs_logincidadao.security.authentication.listener:
        class: PROCERGS\LoginCidadao\CoreBundle\Security\Http\Firewall\LoginCidadaoListener
        parent: security.authentication.listener.form
        abstract: true
        calls:
            - [setContainer, ["@service_container"]]

    procergs_logincidadao.user_register:
        class: %procergs_logincidadao.user_register.class%
        arguments: ["@router", "@session", "@translator", "@fos_user.mailer", "@fos_user.util.token_generator", "@notifications.helper", "%registration.email.unconfirmed_time%"]
        tags:
            - { name: kernel.event_subscriber }
        calls:
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]

    procergs_logincidadao.profile_edit:
        class: %procergs_logincidadao.profile_edit.class%
        arguments: ["@procergs_logincidadao.mailer", "@fos_user.mailer", "@fos_user.util.token_generator", "@router", "@session", "@security.context", "@notifications.helper", "%registration.email.unconfirmed_time%"]
        tags:
            - { name: kernel.event_subscriber }
        calls:
            - [setCpfEmptyTime, ["%registration.cpf.empty_time%"]]
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]
            - [setDneHelper, ["@procergs_logincidadao.dne"]]
            - [setNfgHelper, ["@procergs_logincidadao.nfgws"]]
            - [setUserManager, ["@fos_user.user_manager"]]

    procergs_logincidadao.change.password.form.type:
        class: %procergs_logincidadao.change.password.form.type.class%
        arguments: [%fos_user.model.user.class%, "@security.context"]
        tags:
            - { name: form.type, alias: procergs_change_password }

    procergs_logincidadao.change_password_listener:
        class: %procergs_logincidadao.change.password.listener.class%
        arguments: ["@router", "@notifications.helper"]
        tags:
            - { name: kernel.event_subscriber }

    procergs_logincidadao.resetting_listener:
        class: %procergs_logincidadao.resetting.listener.class%
        arguments: ["@router", %fos_user.resetting.token_ttl%]
        tags:
            - { name: kernel.event_subscriber }

    procergs_logincidadao.dne:
        class: %procergs_logincidadao.dne.class%
        calls:
            - [setProxy, ["%http_proxy%"]]

    procergs_logincidadao.mailer:
        class: %procergs_logincidadao.mailer.class%
        arguments: [ "@mailer", "@router", "@twig", { "template": { "confirmation": %fos_user.registration.confirmation.template%, "resetting": %fos_user.resetting.email.template%, "email_changed": %procergs_logincidadao_core.emailChanged.template% }, "from_email": { "confirmation": %fos_user.registration.confirmation.from_email%, "resetting": %fos_user.resetting.email.from_email%, "email_changed": %mailer_sender_mail%, "email_sender_name": %mailer_sender_name% } } ]

    kernel.listener.logged_in_user_listener:
        class: %kernel.listener.logged_in_user_listener.class%
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
        arguments: [ "@security.context", "@router", "@session" ]

    kernel.listener.exceptions_listener:
        class: %kernel.listener.exceptions_listener.class%
        arguments: [ "@session", "@router", "@translator" ]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    procergs_logincidadao.client.form.type:
        class: PROCERGS\LoginCidadao\CoreBundle\Form\Type\ClientFormType
        tags:
            - { name: form.type, alias: client_form_type }
        calls:
            - [setContainer, ["@service_container"]]

    procergs_logincidadao.nfgws:
        class: %procergs_logincidadao.nfgws.class%
        calls:
            - [setUrl, [%nfg_ws_url%]]
            - [setOrganizacao, [%soe_organization%]]
            - [setUsuario, [%soe_username%]]
            - [setSenha, [%soe_password%]]
