parameters:
    validation.handler.class: PROCERGS\LoginCidadao\ValidationControlBundle\Handler\ValidationHandler
    validation.idcard.validator.class: PROCERGS\LoginCidadao\ValidationControlBundle\Validator\Constraints\IdCardValidator

services:
    validation.handler:
        class: %validation.handler.class%
        arguments: [ @event_dispatcher ]

    validation.idcard.validator:
        class: %validation.idcard.validator.class%
        arguments: [ @validation.handler ]
        tags:
            - { name: validator.constraint_validator, alias: validation.idcard.validator }