parameters:
    badges.handler.class: PROCERGS\LoginCidadao\BadgesControlBundle\Handler\BadgesHandler
    procergs_login_cidadao_badges_control.subscriber.class: PROCERGS\LoginCidadao\BadgesControlBundle\Event\BadgesSubscriber
    lc_badges_control.serializer.subscriber.class: PROCERGS\LoginCidadao\BadgesControlBundle\Event\SerializationSubscriber

services:
    badges.handler:
        class: %badges.handler.class%
        arguments: [ @event_dispatcher ]
    
    procergs_login_cidadao_badges_control.subscriber:
        class: %procergs_login_cidadao_badges_control.subscriber.class%
        arguments: [ @badges.handler ]
        tags:
            - { name: kernel.event_subscriber }

    lc_badges_control.serializer.subscriber:
        class: %lc_badges_control.serializer.subscriber.class%
        arguments: [ @badges.handler ]
        tags:
            - { name: jms_serializer.event_listener, event: serializer.pre_serialize, method: onPreSerialize }
